/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppGreeting(){
        App classTesting = new App();
        assertNotNull("Greetings from App");
    }

}
