/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.lang.*;

public class App {
//./gradlew run --args '/Users/akachi/Documents/Codefellows/codefellows401/bitmap-transformer/app/src/main/resources/bitMap-image.bmp /Users/akachi/Documents/Codefellows/codefellows401/bitmap-transformer/app/src/main/resources/bitMap-image2.bmp red'

    public static void main(String[] args)throws IOException  {
        File image = new File("app/src/main/resources/bitMap-image.bmp");
        try {
            BufferedImage imageStream = ImageIO.read(image);
        } catch (IOException e) {
            e.printStackTrace();
        }
//        System.out.println(imageStream);

        Bitmap bitMapFromFile = null;
        if (args.length > 0) {
            String file = args[0];
            try {
                bitMapFromFile = new Bitmap(file);
            } catch (IOException e) {
                e.printStackTrace();
            }

            if (args[2].equals("red")) {
                bitMapFromFile.convertToReds();
            }
            if (args[2].equals("grayscale")) {
                bitMapFromFile.convertToGrayScale();
            }
            if (args[2].equals("pink")) {
                bitMapFromFile.convertToPink();
            }
            else {
                System.out.println("Something went wrong!");
            }
        }

        try {
            bitMapFromFile.write(args[1]);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

}
//bitmap-transformer/app/src/main/java/bitmap.transformer/app